import { FormEvent, type ReactNode, useEffect, useState } from 'react'
import { Logo } from '../components/Logo'

const api = import.meta.env.VITE_API_BASE_URL ?? 'http://127.0.0.1:8000'
type Comparison = { fixed_output_kwh:number; tracked_output_kwh:number; efficiency_gain_pct:number; session_id:string|null; data_source?:string }
type Sun = { solar_azimuth:number; solar_elevation:number; optimal_panel_tilt_angle:number }
type Progress = { earth_kardashev_value:number; session_efficiency_gain_pct:number; projected_k_shift:number; projection:{label:string} }
type Usage = {captured_kwh:number;consumed_kwh:number;waste_kwh:number;deficit_kwh:number;flagged_windows:{window:string;waste_kwh:number}[]}
type Absorption={zones:{lat:number;lng:number;avg_irradiance:number;potential_score:number}[]}; type Distribution={allocations:Record<string,number>;shortfalls:{sector:string;shortfall_kwh:number}[]}; type Recommendations={recommendations:{priority:'high'|'medium'|'low';action:string;reason:string}[]}
const nav=['Overview','Tracker Control','Kardashev Progress','Sun Position','Usage Intelligence','Absorption Optimization','Distribution Logic','Recommendation Engine']
const today=(offset:number)=>{const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)}
async function post<T>(path:string,body:object){const response=await fetch(`${api}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail??'The request could not be completed.');return data as T}

export function Dashboard(){
 const [view,setView]=useState('Overview'),[lat,setLat]=useState('28.6139'),[lng,setLng]=useState('77.2090'),[start,setStart]=useState(today(-7)),[end,setEnd]=useState(today(-1)),[area,setArea]=useState('2'),[eff,setEff]=useState('22')
 const [comparison,setComparison]=useState<Comparison|null>(null),[progress,setProgress]=useState<Progress|null>(null),[sun,setSun]=useState<Sun|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [consumed,setConsumed]=useState('4'),[usage,setUsage]=useState<Usage|null>(null),[absorption,setAbsorption]=useState<Absorption|null>(null),[distribution,setDistribution]=useState<Distribution|null>(null),[recommendations,setRecommendations]=useState<Recommendations|null>(null)
 const sunRequest=async()=>{try{setSun(await post<Sun>('/api/tracker/sun-position',{latitude:+lat,longitude:+lng,timestamp:new Date().toISOString()}));setError('')}catch(e){setError(e instanceof Error?e.message:'Sun position unavailable.')}}
 useEffect(()=>{void sunRequest();const timer=window.setInterval(()=>void sunRequest(),60000);return()=>window.clearInterval(timer)// eslint-disable-next-line react-hooks/exhaustive-deps
 },[lat,lng])
 const comparisonRequest=async(event?:FormEvent)=>{event?.preventDefault();setBusy(true);setError('');setProgress(null);try{const result=await post<Comparison>('/api/tracker/compare',{latitude:+lat,longitude:+lng,start_date:start,end_date:end,panel_specs:{area_m2:+area,efficiency_pct:+eff}});setComparison(result);if(result.session_id)setProgress(await post<Progress>('/api/tracker/kardashev-score',{session_id:result.session_id}));else setError('Comparison complete. Configure Supabase to persist a session and unlock the global projection.')}catch(e){setError(e instanceof Error?e.message:'Comparison unavailable.')}finally{setBusy(false)}}
 const module=async<T,>(path:string,payload:object,setter:(x:T)=>void)=>{setBusy(true);setError('');try{setter(await post<T>(path,payload))}catch(e){setError(e instanceof Error?e.message:'Module unavailable.')}finally{setBusy(false)}}
 const max=comparison?Math.max(comparison.fixed_output_kwh,comparison.tracked_output_kwh,.0001):1
 let content:ReactNode
 if(view==='Overview')content=<Overview/>
 else if(view==='Tracker Control')content=<section className="standalone-page" id="tracker-control"><span className="eyebrow">Tracker Control</span><h2>Panel comparison</h2><form className="comparison-form" onSubmit={comparisonRequest}><Field label="Start" type="date" value={start} set={setStart}/><Field label="End" type="date" value={end} set={setEnd}/><Field label="Area m²" type="number" value={area} set={setArea}/><Field label="Efficiency %" type="number" value={eff} set={setEff}/><button className="outline-button" disabled={busy}>{busy?'Calculating':'Run comparison'}</button></form>{busy&&<div className="skeleton comparison-skeleton"/>}{error&&<Failure message={error} retry={()=>void comparisonRequest()}/>} {comparison&&<><p className="cached-label">{comparison.data_source==='cached_demo_sample'?'Showing cached sample data — NASA POWER was unavailable.':'Live NASA POWER comparison data.'}</p><div className="gain-stat"><span>Efficiency gain</span><strong>+{comparison.efficiency_gain_pct.toFixed(2)}%</strong></div><div className="bar-comparison"><Bar label="Fixed tilt" value={comparison.fixed_output_kwh} width={comparison.fixed_output_kwh/max*100}/><Bar label="Sun tracking" value={comparison.tracked_output_kwh} width={comparison.tracked_output_kwh/max*100} glow/></div></>}</section>
 else if(view==='Kardashev Progress')content=<section className="standalone-page" id="kardashev-progress"><span className="eyebrow">Kardashev Progress</span><h2>Earth-scale measure</h2><div className="progress-content"><Logo fillPercent={(progress?.earth_kardashev_value??.73)*100} size={220}/><div><span className="eyebrow">Earth Kardashev value</span><strong className="k-value">{progress?.earth_kardashev_value.toFixed(6)??'0.730000'}</strong></div></div>{progress?<><div className="support-stats"><span>Session gain <b>+{progress.session_efficiency_gain_pct.toFixed(2)}%</b></span><span>Projected K shift <b>+{progress.projected_k_shift.toFixed(6)}</b></span></div><p className="estimate-label">{progress.projection.label}</p></>:<p className="estimate-label">Run Tracker Control first to create a comparison session.</p>}{error&&<Failure message={error}/>}</section>
 else if(view==='Sun Position')content=<section className="standalone-page"><span className="eyebrow">Live tracker · 60s refresh</span><h2>Sun position</h2>{sun&&<div className="sun-stats"><Stat label="Azimuth" value={`${sun.solar_azimuth.toFixed(1)}°`}/><Stat label="Elevation" value={`${sun.solar_elevation.toFixed(1)}°`}/><Stat label="Optimal tilt" value={`${sun.optimal_panel_tilt_angle.toFixed(1)}°`}/></div>}{error&&<Failure message={error} retry={()=>void sunRequest()}/>}</section>
 else if(view==='Usage Intelligence')content=<Module title={view} eyebrow="Captured versus consumed" busy={busy} error={error} action="Analyze usage" onAction={()=>void module('/api/usage/analyze',{captured_kwh:comparison?.tracked_output_kwh??0,consumed_kwh:+consumed},setUsage)}><Field label="Consumed kWh" type="number" value={consumed} set={setConsumed}/>{usage&&<><div className="module-stat-grid"><Stat label="Captured" value={`${usage.captured_kwh.toFixed(2)} kWh`}/><Stat label="Consumed" value={`${usage.consumed_kwh.toFixed(2)} kWh`}/><Stat label="Waste" value={`${usage.waste_kwh.toFixed(2)} kWh`}/><Stat label="Deficit" value={`${usage.deficit_kwh.toFixed(2)} kWh`}/></div><List title="Highest waste windows" items={usage.flagged_windows.map(x=>[x.window,`${x.waste_kwh.toFixed(3)} kWh`])}/></>}</Module>
 else if(view==='Absorption Optimization')content=<Module title={view} eyebrow="NASA POWER potential grid" busy={busy} error={error} action="Rank zones" onAction={()=>void module('/api/absorption/zones',{center_lat:+lat,center_lng:+lng,radius_km:10,grid_size:3},setAbsorption)}>{absorption&&<List title="Ranked zones" items={absorption.zones.map(x=>[`${x.lat}, ${x.lng}`,`Score ${x.potential_score.toFixed(2)} · GHI ${x.avg_irradiance.toFixed(2)}`])}/>}</Module>
 else if(view==='Distribution Logic')content=<Module title={view} eyebrow="40% residential · 40% industrial · 20% agricultural" busy={busy} error={error} action="Model allocation" onAction={()=>void module('/api/distribution/model',{total_captured_kwh:comparison?.tracked_output_kwh??0,demand_breakdown:{residential_pct:40,industrial_pct:40,agricultural_pct:20}},setDistribution)}>{distribution&&<><div className="allocation-list">{Object.entries(distribution.allocations).map(([key,value])=><Bar key={key} label={key.replace('_kwh','')} value={value} width={Math.min(100,value)} glow/>)}</div><List title="Shortfalls" items={distribution.shortfalls.map(x=>[x.sector,`${x.shortfall_kwh.toFixed(2)} kWh`])}/></>}</Module>
 else content=<Module title={view} eyebrow="Explainable rule set" busy={busy} error={error} action="Generate recommendations" onAction={()=>void module('/api/recommendations/generate',{usage,absorption,distribution},setRecommendations)}>{recommendations&&<div className="recommendations">{recommendations.recommendations.map((x,i)=><article className={`recommendation ${x.priority}`} key={i}><span>{x.priority}</span><h3>{x.action}</h3><p>{x.reason}</p></article>)}</div>}</Module>
 return <main className="dashboard-shell"><aside className="sidebar"><div className="sidebar-mark"><Logo size={38}/></div><nav aria-label="Dashboard sections">{nav.map((item,i)=><button className={`nav-item ${view===item?'active':''}`} key={item} onClick={()=>setView(item)}><span>{i<4?'◈':'○'}</span><span>{item}</span></button>)}</nav></aside><section className="dashboard-workspace"><header className="topbar"><div><span className="eyebrow">Kardashev Scaler</span><h1>{view}</h1></div><div className="location-fields"><Field label="Lat" value={lat} set={setLat}/><Field label="Lng" value={lng} set={setLng}/></div></header><section className="view-transition" key={view}>{content}</section></section></main>
}

function Overview(){const [active,setActive]=useState(0);useEffect(()=>{const update=()=>{const el=document.getElementById('kardashev-story');if(!el)return;const n=Math.max(0,Math.min(1,(scrollY-el.offsetTop)/(el.offsetHeight-innerHeight)));setActive(n<.33?0:n<.66?1:2)};update();addEventListener('scroll',update,{passive:true});return()=>removeEventListener('scroll',update)},[]);const types=[['Type I','Harness all of the energy on a planet'],['Type II','Harness all of the energy from a star'],['Type III','Harness all of the energy in a galaxy']];return <div className="overview-page"><section className="overview-intro"><span className="eyebrow">A measure of energy</span><h2>What is the Kardashev Scale</h2><p>The Kardashev Scale measures a civilization by the energy it can harness. Type I uses the energy of a planet; Type II draws on a star; Type III operates across a galaxy. Earth is still approaching Type I, at approximately 0.73.</p></section><section id="kardashev-story" className="story-container"><div className="story-sticky"><div className="story-media">{types.map((_,i)=><div id={`media-${i+1}`} className={`story-media-layer ${active===i?'active':''}`} key={i}/>)}</div><div className="story-copy"><span className="eyebrow">Kardashev Scaler</span><h2>We aspire to be a galactic civilization</h2><div className="story-rows">{types.map(([type,text],i)=><div className={`story-row ${active===i?'active':''}`} key={type}><b>{type}</b><span>— {text}</span></div>)}</div></div></div></section><section className="about-section"><span className="eyebrow">About Kardashev Scaler</span><h2>From sunlight to civilization-scale context</h2><h3>What it does</h3><p>Kardashev Scaler tracks real sun position, compares fixed and tracked solar panel output using NASA data, and maps results onto the real Kardashev Scale.</p><h3>Why it matters</h3><p>Tracking and optimising solar capture turns a practical local gain into a clearer view of global energy progress.</p><h3>How to use it</h3><ol><li>Enter a location in the global top bar.</li><li>Run a panel comparison in Tracker Control.</li><li>View Kardashev Progress.</li><li>Explore Usage, Absorption, Distribution, and Recommendation modules.</li></ol></section></div>}
function Field({label,value,set,type='text'}:{label:string;value:string;set:(value:string)=>void;type?:string}){return <label>{label}<input type={type} value={value} onChange={e=>set(e.target.value)}/></label>}
function Module({title,eyebrow,busy,error,action,onAction,children}:{title:string;eyebrow:string;busy:boolean;error:string;action:string;onAction:()=>void;children:ReactNode}){return <section className="module-page"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><div className="module-action"><button className="outline-button" disabled={busy} onClick={onAction}>{busy?'Processing':action}</button></div>{busy&&<div className="skeleton module-skeleton"/>}{error&&<Failure message={error} retry={onAction}/>} {children}</section>}
function Bar({label,value,width,glow=false}:{label:string;value:number;width:number;glow?:boolean}){return <div className="output-row"><div><span>{label}</span><b>{value.toFixed(3)} kWh</b></div><div className="output-track"><i className={glow?'glow-bar':''} style={{width:`${width}%`}}/></div></div>};function Stat({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>};function Failure({message,retry}:{message:string;retry?:()=>void}){return <div className="failure"><p>{message}</p>{retry&&<button className="text-button" onClick={retry}>Retry</button>}</div>};function List({title,items}:{title:string;items:string[][]}){return <div className="data-list"><span className="eyebrow">{title}</span>{items.length?items.map(([a,b])=><p key={a}><b>{a}</b><span>{b}</span></p>):<p>No items flagged.</p>}</div>}
